In [2]:
import pandas as pd
import numpy as np

In [4]:
import pandas as pd

data = {
    "YearsExperience": [1.1, 1.3, 1.5, 2.0, 2.2, 2.9, 3.0, 3.2, 3.5, 3.7],
    "Salary": [39343, 46205, 37731, 43525, 39891, 56642, 60150, 54445, 64445, 57189]
}

df = pd.DataFrame(data)
df.to_csv("Salary_Data.csv", index=False)

print("Salary_Data.csv created!")

Salary_Data.csv created!

In [5]:
df = pd.read_csv("Salary_Data.csv")

In [6]:
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [8]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [10]:
mean = df['Salary'].mean()
print(mean)

49956.6

In [11]:
median = df['Salary'].median()
print(median)

50325.0

In [13]:
print(df.columns)

Index(['YearsExperience', 'Salary'], dtype='str')

In [14]:
grouped_stats = df.groupby('YearsExperience')['Salary'].mean()
print(grouped_stats)

YearsExperience
1.1    39343.0
1.3    46205.0
1.5    37731.0
2.0    43525.0
2.2    39891.0
2.9    56642.0
3.0    60150.0
3.2    54445.0
3.5    64445.0
3.7    57189.0
Name: Salary, dtype: float64

In [19]:
print(float(grouped_stats.mean()))

49956.6

In [20]:
print(float(grouped_stats.median()))

50325.0

In [21]:
print(float(grouped_stats.min()))

37731.0

In [22]:
grouped_stats.std()

np.float64(9717.322107110236)

In [23]:
grouped_stats.agg(['mean'])

mean    49956.6
Name: Salary, dtype: float64

In [24]:
grouped_stats.agg(['mean','median','min','max','std'])

mean      49956.600000
median    50325.000000
min       37731.000000
max       64445.000000
std        9717.322107
Name: Salary, dtype: float64

In [26]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
df1 = pd.DataFrame(iris.data, columns=iris.feature_names)
df1['species'] = iris.target

print(df1.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   species
0        0
1        0
2        0
3        0
4        0

In [27]:
df1.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [28]:
df1.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [30]:
print(df1.columns)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='str')

In [31]:
grouped_stats1 = df1.groupby('species')['sepal length (cm)']

In [32]:
grouped_stats1.agg(['mean','median','min','max','std'])

          mean  median  min  max       std
species
0        5.006     5.0  4.3  5.8  0.352490
1        5.936     5.9  4.9  7.0  0.516171
2        6.588     6.5  4.9  7.9  0.635880

In [34]:
Setosa = df1[df1['species'] == 'setosa']

In [35]:
Versicolor  = df1[df1['species'] == 'versicolor']

In [36]:
Virginica   = df1[df1['species'] == 'virginica']

In [37]:
print(df1['species'].unique())

[0 1 2]